FROM ubuntu:latest

# Install dependencies

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.9 \
                       python3.9-distutils \
                       python3-pip \
                       p7zip-full \
                       wget \
                       bzip2 \
                       ca-certificates \
                       curl \
                       git \
                       unzip

# Install Miniconda
RUN curl -o /tmp/miniconda.sh -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x /tmp/miniconda.sh && \
    /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# Set up Miniconda environment
ENV PATH /opt/conda/bin:$PATH

# Install Python packages
RUN pip3 install jupyter pandas numpy scipy matplotlib python-arango xmltodict tqdm

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*