# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Install MLflow
RUN pip install mlflow

# Expose the port the app runs on
EXPOSE 5000

# Set environment variables
ENV MLFLOW_SERVER_HOST=0.0.0.0
ENV MLFLOW_SERVER_PORT=5000

# Run MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]